### Підготовка

In [1]:
import pandas as pd

In [8]:
df_raw = pd.read_csv('survey_results_public.csv', low_memory=False)
schema_raw = pd.read_csv('survey_results_schema.csv')

In [71]:
df_raw.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [72]:
schema_raw.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [42]:
df = df_raw.copy()

In [5]:
print("Structure:")
df.info()
print("\n" + "="*50 + "\n")

print("Countries:")
print(df['Country'].value_counts().head(10))
print("\n" + "="*50 + "\n")

print("Age groups:")
print(df['Age'].unique())
print("\n" + "="*50 + "\n")

print(f"Duplicates: {df.duplicated().sum()}")
print("\n" + "="*50 + "\n")

print(f"Missing values: \n {df.isnull().sum()}")
print("\n" + "="*50 + "\n")

Structure:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

==================================================

Countries:
Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
Canada                                                  1305
Ukraine                                                  964
Poland                                                   888
Netherlands                                              867
Italy                                                    835
Name: count, dtype: int64

==================================================

Age groups:
['25-34 years old' '35-44 years old' '45-54 years old' '18-24 years old'
 '65 years or older' '55-64 years old' 'Prefer not to say']

==================================================

Duplicates: 0

==================================================

Missing values:
 ResponseId                 0
MainBranch                 0
Age                        0
EdLevel                 1042
Employment               852
                       ...
AIAgentExtWrite        48332
AIHuman                19997
AIOpen                 26651
ConvertedCompYearly    25244
JobSat                 22521
Length: 172, dtype: int64

==================================================

In [60]:
no_country = df['Country'].isna()
print(f"Missing country values: {no_country.sum()}")
print(f"Missing values columns: {df[no_country].isna().all().sum()}")

Missing country values: 13754
Missing values columns: 110

### Завдання 1. Підрахунок загальної кількості респондентів

In [49]:
total_res = df.shape[0]
total_res

49191

### Завдання 2. Аналіз повноти відповідей респондентів

In [44]:
schema = set(schema_raw["qname"])
df_col = set(df.columns)
cols = list(schema & df_col)
df.dropna(subset=cols).shape[0]

0

Жоден респонден невідповів на всі питання

### Завдання 3. Статистичний аналіз досвіду респондентів

In [45]:
work_mean = df['WorkExp'].mean()
work_median = df['WorkExp'].median()
work_mode = df['WorkExp'].mode()[0]

print(f"Mean: {work_mean:.2f}")
print(f"Median: {work_median}")
print(f"Moda: {work_mode}")

Mean: 13.37
Median: 10.0
Moda: 10.0

### Завдання 4. Аналіз віддаленої роботи

In [46]:
rem = df['RemoteWork'] == 'Remote'
df[rem].shape[0]

10931

### Завдання 5. Визначення популярності Python

In [57]:
p_users = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
p_users_count = df[p_users].shape[0]
p_users_pr = (p_users_count/total_res) * 100
print(f"Python users: {p_users_pr:.2f}%")

Python users: 37.54%

### Завдання 6. Аналіз шляхів навчання програмуванню

In [63]:
df['LearnCode'].head(10)

0    Online Courses or Certification (includes all ...
1    Online Courses or Certification (includes all ...
2    Online Courses or Certification (includes all ...
3    Other online resources (e.g. standard search, ...
4                                                  NaN
5    Online Courses or Certification (includes all ...
6    Videos (not associated with specific online co...
7    Books / Physical media;Technical documentation...
8    Online Courses or Certification (includes all ...
9    Other online resources (e.g. standard search, ...
Name: LearnCode, dtype: object

In [64]:
online_learners = df['LearnCode'].str.contains('Online Courses', na=False)
online_learners_count = df[online_learners].shape[0]
online_learners_count

10973

### Завдання 7. Географічний аналіз компенсації Python-розробників

In [65]:
python_df = df[df['LanguageHaveWorkedWith'].str.contains('Python', na=False)].copy()

In [70]:
salary_by_country = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
salary_by_country['count'] = python_df.groupby('Country')['ConvertedCompYearly'].count()
salary_by_country = salary_by_country.sort_values(by='median', ascending=False)

top_countries = salary_by_country[salary_by_country['count'] > 50]
top_countries.style.format("{:.2f}")

### Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [69]:
top = df.sort_values(by='ConvertedCompYearly', ascending=False).head(5)
res = top[['ConvertedCompYearly', 'EdLevel']]
res

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)